### ISSUE TITLE
`code` formatting overrides `pre > code` formatting

### ISSUE THREAD

**Issue by davestewart** [spectre-org/spectre-css#25]
## Bug description

In the docs, the formatting for code overrides common formatting for `pre > code` used by modern code styling libs:

![image](https://github.com/spectre-org/spectre-css/assets/132681/796f6d96-4ccf-4223-b62c-52fec1c8901f)

Should we prevent this with something like:

```scss
  pre code {
    background: unset;
    color: unset;
  }
```

?
