### ISSUE TITLE
Fix experimental Meter component

### ISSUE THREAD

**Issue by davestewart** [spectre-org/spectre-css#42]
## Background

The library currently includes the experimental [Meter](https://spectre-org.github.io/spectre-docs/docs/experimentals/meters.html) component. Unfortunately, it seems buggy on both this fork and the [original](https://picturepan2.github.io/spectre/experimentals/meters.html).

However, I've asked Claude AI if it's fixable, and apparently it is.

## Proposal

Claude created the following HTML which rendered nicely:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Styled Meter Element Example</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f0f0f0;
        }
        .container {
            text-align: center;
        }
        meter {
            width: 300px;
            height: 25px;
            margin-bottom: 20px;
            border-radius: 12px; /* Added border-radius */
        }
        meter::-webkit-meter-bar {
            background: #e0e0e0;
            border: 1px solid #ccc;
            border-radius: 12px; /* Match the meter's border-radius */
        }
        meter::-webkit-meter-optimum-value {
            background: #00ff00;
            border-radius: 12px; /* Match the meter's border-radius */
        }
        meter::-webkit-meter-suboptimum-value {
            background: #ffff00;
            border-radius: 12px; /* Match the meter's border-radius */
        }
        meter::-webkit-meter-even-less-good-value {
            background: #ff0000;
            border-radius: 12px; /* Match the meter's border-radius */
        }
        label {
            display: block;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Styled Meter Element</h1>
        <label for="meter1">Optimum Value (0.7):</label>
        <meter id="meter1" value="0.7" min="0" max="1" optimum="0.8" low="0.4" high="0.9"></meter>
        
        <label for="meter2">Suboptimum Value (0.5):</label>
        <meter id="meter2" value="0.5" min="0" max="1" optimum="0.8" low="0.4" high="0.9"></meter>
        
        <label for="meter3">Less Good Value (0.2):</label>
        <meter id="meter3" value="0.2" min="0" max="1" optimum="0.8" low="0.4" high="0.9"></meter>
    </div>
</body>
</html>
```

There is also Firefox styling to be included:

```css
meter {
    width: 300px;
    height: 25px;
    margin-bottom: 20px;
    border-radius: 12px;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}

/* WebKit/Blink browsers */
meter::-webkit-meter-bar {
    background: #e0e0e0;
    border: 1px solid #ccc;
    border-radius: 12px;
}
meter::-webkit-meter-optimum-value,
meter::-webkit-meter-suboptimum-value,
meter::-webkit-meter-even-less-good-value {
    border-radius: 12px;
}

/* Firefox */
meter::-moz-meter-bar {
    border-radius: 12px;
}

/* Fallback for browsers that don't support custom styling */
meter {
    background: #e0e0e0;
    border: 1px solid #ccc;
}
```
